
sudo: required

services:
    - docker

before_install:
    - docker pull icepack/firedrake:latest
    - docker run --interactive --tty --detach --volume $TRAVIS_BUILD_DIR:/repo --name build icepack/firedrake:latest

install:
    - docker exec -i build bash -c ". /firedrake/bin/activate && cd /repo && pip3 install -e ."

script:
    - docker exec -i build bash -c ". /firedrake/bin/activate && cd /repo && MPLBACKEND='Agg' pytest --capture=no --verbose"

