
sudo: required

services:
    - docker

before_install:
    - docker pull icepack/firedrake:stretch
    - chmod --recursive a+rwx $TRAVIS_BUILD_DIR
    - >
      docker run --interactive --tty --detach --name build
      --volume $TRAVIS_BUILD_DIR:/home/user/icepack
      --workdir /home/user/icepack
      icepack/firedrake:stretch

install:
    - docker exec -i build bash -c "pip3 install --editable ."

script:
    - docker exec -i build bash -c "MPLBACKEND='Agg' pytest -W ignore::DeprecationWarning --capture=no --verbose"
