version: 2.1

commands:
  build:
    steps:
      - checkout
      - run: pip3 install --editable .
      - run: pip3 install pytest-cov codecov
  test:
    steps:
      - run: pytest --capture=no --verbose --cov=icepack
  codecov:
    steps:
      - run: codecov

jobs:
  python35:
    docker:
      - image: icepack/firedrake-python3.5:0.3.2
    working_directory: ~/icepack
    steps:
      - build
      - test
  python37:
    docker:
      - image: icepack/firedrake-python3.7:0.3.2
    working_directory: ~/icepack
    steps:
      - build
      - test
      - codecov

workflows:
  version: 2
  tests:
    jobs:
      - python35
      - python37
